AWSTemplateFormatVersion: "2010-09-09"
Description: Launch a simple EC2 for testing VPCs 
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
  VpcId:
    Type: String
    Default: vpc-08d2c45b7c141e0f3
  ImageId:
    Type: String
    Default: ami-0058d1c948f990db0
  SubnetId:
    Type: String
    Default: subnet-0e68212b138b2b5f0
Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId 
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetId
          AssociatePublicIpAddress: true
          GroupSet:
            - !GetAtt SG.GroupId
          DeleteOnTermination: true
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          # Update and install Apache HTTP Server
          yum update -y
          yum install -y httpd
          # Start the Apache service
          systemctl start httpd
          # Enable Apache to start on boot
          systemctl enable httpd
          # Create a simple HTML page
          echo "<html><body><h1>Welcome to Apache on EC2</h1></body></html>" > /var/www/html/index.html
  SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        # -1 allows all traffic
        - IpProtocol: -1 
          FromPort: -1 
          ToPort: -1 
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1 
          FromPort: -1 
          ToPort: -1 
          CidrIp: 0.0.0.0/0