#!/usr/bin/env bash

set -e

# Create VPC
VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--region ap-northeast-1 \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc}]' \
--query 'Vpc.VpcId' \
--output text)

echo "VPC_ID = $VPC_ID"

#Turn on DNS hostname
aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-hostnames "{\"Value\":true}"

# Create an IGW
IGW_ID=$(aws ec2 create-internet-gateway \
  --region ap-northeast-1 \
  --query 'InternetGateway.InternetGatewayId' \
  --output text)

echo "IGW_ID = $IGW_ID"

# Attach an IGW
aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# Create a new subnet
SUBNET_ID=$(aws ec2 create-subnet \
--vpc-id $VPC_ID --cidr-block 172.1.0.0/20 \
--query Subnet.SubnetId \
--output text)

echo "SUBNET_ID = $SUBNET_ID"

#Auto-assign IPv4 address
aws ec2 modify-subnet-attribute \
--subnet-id $SUBNET_ID \
--map-public-ip-on-launch

# Get the route table
RT_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--query 'RouteTables[0].RouteTableId' \
--output text)

echo "RT_ID = $RT_ID"

# Associate the subnet
ASSOC_ID=$(aws ec2 associate-route-table \
--route-table-id $RT_ID \
--subnet-id $SUBNET_ID \
--query AssociationId \
--output text)

#Add a route from our route table to IGW
aws ec2 create-route \
--route-table-id $RT_ID \
--destination-cidr-block 0.0.0.0/0 \
--gateway-id $IGW_ID

echo "./delete-vpc $VPC_ID $IGW_ID $SUBNET_ID $ASSOC_ID $RT_ID"