#!/usr/bin/env bash
echo "== sync"

set -e

#Check for bucket name 
if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

#Check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a filename prefix"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

OUTPUT_DIR="/tmp/s3-bash-scripts"

rm -r $OUTPUT_DIR

mkdir -p $OUTPUT_DIR

NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++)); do
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

#    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>dev/null
    touch $FILENAME
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files